# Generated by Django 5.0.3 on 2024-05-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('New Order', 'New Order'), ('New Review', 'New Review'), ('New Course Question', 'New Course Question'), ('Course Published', 'Course Published'), ('Draft', 'Draft'), ('Course Enrollment Completed', 'Course Enrollment Completed')], max_length=100),
        ),
    ]
