# Generated by Django 5.0.3 on 2024-06-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_enrolledcourse_order_item_alter_review_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
