# Generated by Django 5.0.3 on 2024-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_thread_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=100),
        ),
    ]
